//! Generate `src/types/generated.ts` from the Rust types (Resolved Decision:
//! ts-rs, build-integrated, CI staleness check). This is the single source of the
//! frontend's types; hand-editing `generated.ts` is forbidden.
//!
//! Run from the repo root: `cargo run -p popush-core --example generate_types`.
//! CI runs this then `git diff --exit-code src/types/generated.ts`, so a stale
//! file fails the build.

use std::fmt::Write as _;

use popush_core::adapters::Capabilities;
use popush_core::command_log::{CommandLogEntry, CommandOutcome};
use popush_core::config::{
    ChangeKind, ChangedFile, Config, GitStatus, Preferences, ServerConfig, ServiceConfig,
    SiteConfig, SiteStatus, Theme,
};
use popush_core::error::{
    AdapterError, AppError, AuthFailureReason, ConfigError, GitError, NextAction, PipelineError,
    SshError, UserMessage,
};
use popush_core::ids::{PipelineId, ServerId, SiteId, StreamId};
use popush_core::ssh::HostKeyDecision;
use popush_core::wizard::{Check, CheckStatus, Fix, FixPreview};
use ts_rs::TS;

/// Push one type's `export type …` declaration.
macro_rules! decl {
    ($out:expr, $($t:ty),+ $(,)?) => {
        $(
            writeln!($out, "export {}\n", <$t as TS>::decl()).unwrap();
        )+
    };
}

fn main() {
    let mut out = String::new();
    out.push_str(
        "// GENERATED by `cargo run -p popush-core --example generate_types`.\n\
         // Source of truth: the Rust types in popush-core. DO NOT EDIT BY HAND.\n\
         // CI fails if this file is stale (Resolved Decision: ts-rs).\n\n",
    );

    // Identifiers.
    decl!(out, ServerId, SiteId, PipelineId, StreamId);
    // Config and domain types.
    decl!(
        out,
        Config,
        Preferences,
        Theme,
        ServerConfig,
        SiteConfig,
        ServiceConfig,
        SiteStatus,
        GitStatus,
        ChangedFile,
        ChangeKind
    );
    // Also export the flat service kind used in TOML.
    decl!(out, popush_core::config::schema::ServiceKind);
    // Adapters.
    decl!(out, Capabilities);
    // SSH.
    decl!(out, HostKeyDecision);
    // Errors and messages.
    decl!(
        out,
        UserMessage,
        NextAction,
        AppError,
        AuthFailureReason,
        SshError,
        GitError,
        AdapterError,
        ConfigError,
        PipelineError
    );
    // Pipeline.
    decl!(
        out,
        popush_core::pipeline::Step,
        popush_core::pipeline::StepState,
        popush_core::pipeline::StepOutcome,
        popush_core::pipeline::PipelineState,
        popush_core::pipeline::step::StepEntry
    );
    // Wizard.
    decl!(out, Check, CheckStatus, FixPreview, Fix);
    // Command log.
    decl!(out, CommandOutcome, CommandLogEntry);

    // Write relative to the repo root (the workspace dir), which is the cwd when
    // invoked with `-p popush-core` from the root.
    let path = std::path::Path::new("src/types/generated.ts");
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent).expect("create src/types");
    }
    std::fs::write(path, out).expect("write generated.ts");
    eprintln!("wrote {}", path.display());
}
