// GENERATED by `cargo run -p popush-core --example generate_types`.
// Source of truth: the Rust types in popush-core. DO NOT EDIT BY HAND.
// CI fails if this file is stale (Resolved Decision: ts-rs).

export type ServerId = string;

export type SiteId = string;

export type PipelineId = string;

export type StreamId = string;

export type Config = { 
/**
 * Schema version for forward-migration. Absent in v1 files means version 1.
 */
schema_version: number, 
/**
 * User preferences.
 */
preferences: Preferences, 
/**
 * Configured servers. Renamed to `server` in TOML for `[[server]]` tables.
 */
server: Array<ServerConfig>, };

export type Preferences = { 
/**
 * Theme selection.
 */
theme: Theme, 
/**
 * Accent colour key. Only "violet" is defined in v1 (Resolved Decision).
 */
accent: string, 
/**
 * Background poll interval in seconds; 0 disables polling.
 */
poll_interval_seconds: bigint, 
/**
 * Whether destructive actions (Stop) ask for confirmation.
 */
confirm_destructive: boolean, 
/**
 * Default branch used when a site does not override it.
 */
default_branch: string, };

export type Theme = "system" | "dark" | "light";

export type ServerConfig = { 
/**
 * Stable id, referenced by sites and the UI.
 */
id: ServerId, 
/**
 * Human label shown in the sidebar.
 */
label: string, 
/**
 * Hostname or IP.
 */
host: string, 
/**
 * SSH port.
 */
port: number, 
/**
 * SSH username.
 */
username: string, 
/**
 * Path to the private key. **Never the key itself**.
 */
identity_file: string, 
/**
 * Optional jump host.
 */
proxy_jump: string | null, 
/**
 * Sites hosted on this server. `[[server.site]]` in TOML.
 */
site: Array<SiteConfig>, };

export type SiteConfig = { 
/**
 * Stable id.
 */
id: SiteId, 
/**
 * Human label.
 */
label: string, 
/**
 * Absolute path on the server where the repo/site lives.
 */
remote_path: string, 
/**
 * How the service runs; selects the adapter.
 */
service_type: ServiceKind, 
/**
 * Compose project, unit name, or pm2 app name (unused for static).
 */
service_name: string | null, 
/**
 * Web root for static sites; defaults to `remote_path` if absent.
 */
web_root: string | null, 
/**
 * Optional build command run on the server during Ship It.
 */
build_command: string | null, 
/**
 * Git remote name (e.g. `origin`).
 */
git_remote: string, 
/**
 * Git branch to deploy.
 */
git_branch: string, 
/**
 * Local clone path for the git panel.
 */
local_path: string | null, 
/**
 * Public URL, shown in the UI.
 */
live_url: string | null, 
/**
 * Optional health check URL; presence upgrades static status honesty.
 */
health_check_url: string | null, };

export type ServiceConfig = { "type": "docker", 
/**
 * Compose project name.
 */
compose_project: string, 
/**
 * Optional explicit compose file.
 */
compose_file: string | null, } | { "type": "systemd", 
/**
 * Unit name.
 */
unit: string, } | { "type": "pm2", 
/**
 * App name.
 */
app_name: string, } | { "type": "static", 
/**
 * Web root directory.
 */
web_root: string, };

export type SiteStatus = { "state": "running", 
/**
 * When it started, if the service reports it.
 */
since: string | null, } | { "state": "stopped" } | { "state": "failed", 
/**
 * Human reason.
 */
reason: string, } | { "state": "unknown", 
/**
 * Why it is unknown, shown in the tooltip.
 */
reason: string, } | { "state": "checking" };

export type GitStatus = { 
/**
 * Current branch name.
 */
branch: string, 
/**
 * Commits ahead of the tracking remote.
 */
ahead: number, 
/**
 * Commits behind the tracking remote.
 */
behind: number, 
/**
 * Changed files.
 */
changed_files: Array<ChangedFile>, 
/**
 * Whether the working tree has unresolved conflicts.
 */
has_conflicts: boolean, 
/**
 * The remote URL.
 */
remote_url: string, 
/**
 * Whether the remote is SSH (true) or HTTPS (false); drives the wizard.
 */
remote_is_ssh: boolean, };

export type ChangedFile = { 
/**
 * Repo-relative path.
 */
path: string, 
/**
 * The kind of change.
 */
change: ChangeKind, 
/**
 * Whether the change is staged.
 */
staged: boolean, };

export type ChangeKind = "added" | "modified" | "deleted" | "renamed" | "untracked";

export type ServiceKind = "docker" | "systemd" | "pm2" | "static";

export type Capabilities = { 
/**
 * Whether start and stop are supported.
 */
can_start_stop: boolean, 
/**
 * Whether restart is supported.
 */
can_restart: boolean, 
/**
 * Whether logs can be tailed.
 */
has_logs: boolean, 
/**
 * Whether the reported status is trustworthy. False for static sites with no
 * health check: the UI shows amber Unknown rather than a fake green.
 */
status_is_reliable: boolean, };

export type HostKeyDecision = { "decision": "trusted" } | { "decision": "unknown", 
/**
 * The fingerprint to show for verification.
 */
fingerprint: string, } | { "decision": "mismatch", 
/**
 * The pinned key Popush expected.
 */
expected: string, 
/**
 * The key actually presented.
 */
got: string, };

export type UserMessage = { 
/**
 * What happened. Specific, the failing step, never "Deploy failed".
 */
headline: string, 
/**
 * What it means for the user. E.g. "Your site is still running the previous
 * version."
 */
consequence: string, 
/**
 * What to do now: an action, a command, or a button the UI can offer.
 */
next_action: NextAction, };

export type NextAction = { "kind": "run_command", 
/**
 * The exact command to display and copy.
 */
command: string, } | { "kind": "open_flow", 
/**
 * The flow identifier (e.g. `"wizard"`).
 */
flow: string, 
/**
 * The button label.
 */
label: string, } | { "kind": "retry" } | { "kind": "advice", 
/**
 * The guidance text.
 */
text: string, };

export type AppError = { "kind": "ssh", "detail": SshError } | { "kind": "git", "detail": GitError } | { "kind": "adapter", "detail": AdapterError } | { "kind": "config", "detail": ConfigError } | { "kind": "pipeline", "detail": PipelineError };

export type AuthFailureReason = { "reason": "agent_rejected" } | { "reason": "no_agent_socket" } | { "reason": "all_methods_exhausted" };

export type SshError = { "code": "host_unreachable", 
/**
 * The host that could not be reached.
 */
host: string, 
/**
 * The underlying OS/network detail.
 */
detail: string, } | { "code": "auth_failed", 
/**
 * The specific reason auth failed.
 */
reason: AuthFailureReason, } | { "code": "host_key_mismatch", 
/**
 * The host whose key changed.
 */
host: string, 
/**
 * The pinned key Popush expected.
 */
expected: string, 
/**
 * The key the server actually presented.
 */
got: string, } | { "code": "host_key_unknown", 
/**
 * The unknown host.
 */
host: string, 
/**
 * The fingerprint for the user to verify.
 */
fingerprint: string, } | { "code": "key_not_in_agent", 
/**
 * Path to the key that is not loaded.
 */
path: string, } | { "code": "key_not_found", 
/**
 * Path that does not exist.
 */
path: string, } | { "code": "command_failed", 
/**
 * The command that was run (safe display form).
 */
command: string, 
/**
 * The non-zero exit code.
 */
exit_code: number, 
/**
 * Captured stderr.
 */
stderr: string, } | { "code": "connection_lost" } | { "code": "timeout", 
/**
 * How long Popush waited, in milliseconds.
 */
after_ms: bigint, };

export type GitError = { "code": "merge_conflicts", 
/**
 * Number of conflicted files.
 */
count: number, 
/**
 * The conflicted paths.
 */
files: Array<string>, } | { "code": "detached_head" } | { "code": "no_upstream", 
/**
 * The branch with no upstream.
 */
branch: string, } | { "code": "https_remote", 
/**
 * The HTTPS remote URL.
 */
url: string, } | { "code": "push_rejected_non_fast_forward" } | { "code": "push_rejected_permission" } | { "code": "operation", 
/**
 * The underlying libgit2 detail.
 */
detail: string, };

export type AdapterError = { "code": "unparseable", 
/**
 * The tool whose output failed to parse (e.g. `docker compose ps`).
 */
tool: string, 
/**
 * The parse detail.
 */
detail: string, } | { "code": "unsupported", 
/**
 * The unsupported operation.
 */
operation: string, 
/**
 * The service type that lacks it.
 */
service_type: string, } | { "code": "ssh" } & SshError;

export type ConfigError = { "code": "unreadable", 
/**
 * The config path.
 */
path: string, 
/**
 * The OS read error detail.
 */
detail: string, } | { "code": "malformed", 
/**
 * The parser's message.
 */
detail: string, } | { "code": "invalid_field", 
/**
 * The offending field path.
 */
field: string, 
/**
 * What is wrong with it.
 */
problem: string, } | { "code": "schema_too_new", 
/**
 * The version found in the file.
 */
found: number, 
/**
 * The highest version this build supports.
 */
supported: number, };

export type PipelineError = { "code": "step_failed", 
/**
 * The step that failed (e.g. `"Build"`).
 */
step: string, 
/**
 * The failure detail.
 */
detail: string, } | { "code": "cancelled", 
/**
 * The step in progress when cancelled.
 */
step: string, 
/**
 * Whether that step was mutating the server.
 */
mid_mutation: boolean, };

export type Step = "check" | "commit" | "push" | "pull" | "build" | "restart" | "verify";

export type StepState = { "state": "pending" } | { "state": "skipped", 
/**
 * Why the step was skipped.
 */
reason: string, } | { "state": "running" } | { "state": "ok", 
/**
 * One-line result summary.
 */
summary: string, 
/**
 * How long the step took, in milliseconds.
 */
duration_ms: bigint, } | { "state": "failed", 
/**
 * One-line failure summary.
 */
summary: string, 
/**
 * How long the step ran before failing, in milliseconds.
 */
duration_ms: bigint, };

export type StepOutcome = "ok" | "failed";

export type PipelineState = { 
/**
 * Per-step state, indexed parallel to [`Step::ALL`].
 */
steps: Array<StepEntry>, 
/**
 * Whether the pipeline has finished (all done, failed, or cancelled).
 */
finished: boolean, 
/**
 * The pre-deploy git SHA, captured for rollback. `None` until Check.
 */
rollback_sha: string | null, };

export type StepEntry = { 
/**
 * Which step.
 */
step: Step, 
/**
 * Its current state.
 */
state: StepState, };

export type Check = "local_key_exists" | "key_in_agent" | "key_on_github" | "local_remote_is_ssh" | "test_push" | "server_can_pull" | "server_remote_is_ssh";

export type CheckStatus = { "status": "pass" } | { "status": "fail", 
/**
 * What is wrong, shown on the expanded row.
 */
what_is_wrong: string, } | { "status": "not_applicable", 
/**
 * Why it does not apply.
 */
why: string, } | { "status": "running" };

export type FixPreview = { 
/**
 * The exact command or change, shown before applying.
 */
command: string, 
/**
 * Plain-English description of what it does.
 */
description: string, 
/**
 * How to undo it. `None` only for inherently safe, additive
 * actions that leave nothing to undo (documented per fix).
 */
undo: string | null, };

export type Fix = { "fix": "generate_local_key", 
/**
 * The previewed command and its undo.
 */
preview: FixPreview, } | { "fix": "convert_remote", 
/**
 * The previewed command and its undo.
 */
preview: FixPreview, };

export type CommandOutcome = { 
/**
 * The process exit code.
 */
exit_code: number, 
/**
 * Captured stdout.
 */
stdout: string, 
/**
 * Captured stderr.
 */
stderr: string, 
/**
 * How long it took, in milliseconds.
 */
duration_ms: bigint, 
/**
 * The exact command sent, safe to display in the log.
 */
command_display: string, };

export type CommandLogEntry = { 
/**
 * When the command was sent.
 */
timestamp: string, 
/**
 * Which server it went to.
 */
server: ServerId, 
/**
 * The exact command sent.
 */
command: string, 
/**
 * The exit code, or `None` if the command did not complete.
 */
exit_code: number | null, 
/**
 * Duration in milliseconds.
 */
duration_ms: bigint, };

export type LatestCommit = { 
/**
 * The abbreviated SHA (first 7 characters).
 */
short_sha: string, 
/**
 * The commit author's display name.
 */
author: string, 
/**
 * The first line of the commit message.
 */
summary: string, };

export type CiStatus = "passing" | "failing" | "pending" | "none";

